apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "astromesh.fullname" . }}-providers
  labels:
    {{- include "astromesh.labels" . | nindent 4 }}
data:
  providers.yaml: |
    {{- .Values.config.providers | nindent 4 }}
