{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "astromesh.fullname" . }}
  labels:
    {{- include "astromesh.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    {{- if .Values.externalSecrets.secretStore.enabled }}
    name: {{ include "astromesh.fullname" . }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
    {{- else }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "SecretStore" }}
    {{- end }}
  target:
    name: {{ include "astromesh.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
{{- end }}
