{{- if or .Values.vllm.huggingfaceToken .Values.tei.huggingfaceToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "astromesh.fullname" . }}-hf-token
  labels:
    {{- include "astromesh.labels" . | nindent 4 }}
type: Opaque
data:
  HF_TOKEN: {{ (.Values.vllm.huggingfaceToken | default .Values.tei.huggingfaceToken) | b64enc | quote }}
{{- end }}
