{{- if .Values.tei.enabled }}
{{- range $i, $instance := .Values.tei.instances }}
{{- if gt $i 0 }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "astromesh.fullname" $ }}-tei-{{ $instance.name }}
  labels:
    {{- include "astromesh.labels" $ | nindent 4 }}
    app.kubernetes.io/component: tei-{{ $instance.name }}
spec:
  type: {{ $.Values.tei.service.type }}
  ports:
    - port: {{ $instance.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "astromesh.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: tei-{{ $instance.name }}
{{- end }}
{{- end }}
